<img src="https://lh6.googleusercontent.com/V4GC83IFE8Bdsl-LYQyj05tYTiy_pjCd_9WhLaSHXC6dGWN3uJ57-b5LNSxWpIaRYxiO-hA76EV2Q5YVD6dkNm9jUekj9NUCILrbZAWgftL6wrhKxLjowUUS7urN7QTqI9ndAqhcih-wT_owvsODG2-wXvS9Zx-jqbW5lX0VbFTFjh62Qm5Y72zCBmu0lw" style="width:400px;height:200px;">
<h1 color="blue">MultiLinear Regression</h1>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
from word2number import w2n
df=pd.read_csv(r"C:\Users\Bezawada\Downloads\hiring.csv")

In [6]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [7]:
experience = df.experience.fillna("zero")
experience

0      zero
1      zero
2      five
3       two
4     seven
5     three
6       ten
7    eleven
Name: experience, dtype: object

In [8]:
import math
median_test_score = math.floor(df['test_score(out of 10)'].mean())
median_test_score

7

In [9]:
df['experience'] = df['experience'].fillna("zero")
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(median_test_score)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    7.0                           7      72000
7     eleven                    7.0                           8      80000

In [10]:
df['experience'] = df['experience'].apply(w2n.word_to_num)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [11]:
reg = linear_model.LinearRegression()
reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])

LinearRegression()

In [12]:
reg.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [13]:
reg.intercept_

14992.65144669314

In [14]:
reg.predict([[10,10,10]])

C:\Users\Bezawada\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([87903.25825647])

In [15]:
2922.26901502*10+ 2221.30909959*10+2147.48256637*10+14992.65144669314

87903.25825649314

In [16]:
reg.predict([[2,9,6]])

C:\Users\Bezawada\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53713.86677124])

In [17]:
reg.predict([[5,6,7]])

C:\Users\Bezawada\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([57964.2290839])

In [18]:
import pickle  #to save the model
with open('Multilinearregressionmodel','wb')as f:
    pickle.dump(reg,f)

In [21]:
with open('Multilinearregressionmodel','rb')as f:
    model= pickle.load(f)

In [22]:
model.predict([[5,6,7]])

C:\Users\Bezawada\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([57964.2290839])

In [24]:
import joblib
joblib.dump(reg,'Model_MLR')

['Model_MLR']

In [25]:
joblib.load('Model_MLR')

LinearRegression()

In [26]:
model.predict([[5,6,7]])

C:\Users\Bezawada\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([57964.2290839])

In [32]:
import pickle
with open('MLR','wb')as f:
    pickle.dump(reg,f)

In [33]:
with open('MLR','rb')as f:
    model=pickle.load(f)

In [34]:
model.predict([[2,3,5]])

C:\Users\Bezawada\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([38238.52960734])